version: 2.1

jobs:

  test_linux:
    docker:
      - image: continuumio/miniconda3:4.7.12
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: create conda env
          command: |
            conda create -n build_env python=3.9 
            source activate build_env
            pip install -r requirements.txt
            pip install .

workflows:
  test-install:
    jobs:
      - test_linux
